server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://andor.ziphost.hu:3306/andor?useSSL=false&serverTimezone=UTC
    username: andor
    password: EUEOpRKLdKvy3YMU
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    org.springframework.security: DEBUG